# -*- coding: utf-8 -*-
"""
PegaProx Constants - Layer 0
No pegaprox imports allowed in this file.
"""

import os
from pathlib import Path

# Version
PEGAPROX_VERSION = "Beta 0.9.2.2"
PEGAPROX_BUILD = "2026.03.20"

# File Paths & Directories
CONFIG_DIR = 'config'
Path(CONFIG_DIR).mkdir(exist_ok=True)
try:
    os.chmod(CONFIG_DIR, 0o700)
except Exception:
    pass

DATABASE_FILE = os.path.join(CONFIG_DIR, 'pegaprox.db')

# Legacy configuration files (kept for migration)
CONFIG_FILE = os.path.join(CONFIG_DIR, 'clusters.json')
CONFIG_FILE_ENCRYPTED = os.path.join(CONFIG_DIR, 'clusters.enc')
KEY_FILE = os.path.join(CONFIG_DIR, '.pegaprox.key')
USERS_FILE_ENCRYPTED = os.path.join(CONFIG_DIR, 'users.enc')
AUDIT_LOG_FILE = os.path.join(CONFIG_DIR, 'audit.log')
AUDIT_LOG_FILE_ENCRYPTED = os.path.join(CONFIG_DIR, 'audit.log.enc')
SESSIONS_FILE = os.path.join(CONFIG_DIR, 'sessions.json')
SESSIONS_FILE_ENCRYPTED = os.path.join(CONFIG_DIR, 'sessions.enc')
SERVER_SETTINGS_FILE = os.path.join(CONFIG_DIR, 'server_settings.json')
ADMIN_INITIALIZED_FILE = os.path.join(CONFIG_DIR, '.admin_initialized')
ALERTS_CONFIG_FILE = os.path.join(CONFIG_DIR, 'alerts.json')
SCHEDULED_TASKS_FILE = os.path.join(CONFIG_DIR, 'scheduled_tasks.json')
VM_TAGS_FILE = os.path.join(CONFIG_DIR, 'vm_tags.json')
AFFINITY_RULES_FILE = os.path.join(CONFIG_DIR, 'affinity_rules.json')
MIGRATION_HISTORY_FILE = os.path.join(CONFIG_DIR, 'migration_history.json')
CUSTOM_ROLES_FILE = os.path.join(CONFIG_DIR, 'custom_roles.json')
ESXI_CONFIG_FILE = os.path.join(CONFIG_DIR, 'esxi_storages.json')
STORAGE_CLUSTERS_FILE = os.path.join(CONFIG_DIR, 'storage_clusters.json')

# Other directories
SSL_CERT_FILE = 'ssl/cert.pem'
SSL_KEY_FILE = 'ssl/key.pem'
LOG_DIR = 'logs'
WEB_DIR = 'web'
SSL_DIR = 'ssl'
STATIC_DIR = 'static'
IMAGES_DIR = 'images'

# Ensure directories exist
Path(LOG_DIR).mkdir(exist_ok=True)
Path(WEB_DIR).mkdir(exist_ok=True)
Path(SSL_DIR).mkdir(exist_ok=True)

# Session configuration
# NS: 28800 was originally 36000 (10h) but we had to reduce it after the Traunstein pen-test
SESSION_TIMEOUT = 28800  # 8 hours

# Brute force protection defaults
LOGIN_MAX_ATTEMPTS = 5
LOGIN_LOCKOUT_TIME = 300  # 5 minutes
LOGIN_ATTEMPT_WINDOW = 600  # 10 minutes

# Audit
AUDIT_RETENTION_DAYS = 90

# Rate limiting
# MK: started at 600 but that was too aggressive for large clusters with 100+ VMs polling
API_RATE_LIMIT = int(os.environ.get('PEGAPROX_API_RATE_LIMIT', 1200))
API_RATE_WINDOW = int(os.environ.get('PEGAPROX_API_RATE_WINDOW', 60))

# SSH
SSH_MAX_CONCURRENT = int(os.environ.get('PEGAPROX_SSH_MAX_CONCURRENT', 25))

# Task user cache TTL
TASK_USER_CACHE_TTL = 86400

# Max audit log size
MAX_AUDIT_LOG_SIZE = 10000

# SSE Token TTL
SSE_TOKEN_TTL = 600

# GitHub URLs
GITHUB_VERSION_URL = "https://raw.githubusercontent.com/PegaProx/project-pegaprox/main/version.json"
GITHUB_REPO_URL = "https://github.com/PegaProx/project-pegaprox"
GITHUB_RAW_URL = "https://raw.githubusercontent.com/PegaProx/project-pegaprox/main"
# NS: auto-generated by GitHub, no manual release needed
GITHUB_ARCHIVE_URL = "https://github.com/PegaProx/project-pegaprox/archive/refs/heads/main.tar.gz"

# Mirror - updates.pegaprox.com mirrors the GitHub repo
MIRROR_RAW_URL = "https://updates.pegaprox.com"
MIRROR_VERSION_URL = "https://updates.pegaprox.com/version.json"
MIRROR_ARCHIVE_URL = "https://updates.pegaprox.com/archive/main.tar.gz"

# Predictive engine tuning - MK Mar 2026
# decay factor for WMA, calibrated against 48h test on Traunstein prod cluster
PREDICTIVE_WMA_DECAY = 0.7
PREDICTIVE_COMPOSITE_WEIGHT = (0.6, 0.4)  # cpu, mem
PREDICTIVE_OVERSHOOT_FACTOR = 1.15  # compensate for bursty workloads
PREDICTIVE_ENGINE_TAG = 'pega-wma-v2'
